insert into trip (trip_name, user_id) values ('Kenya', 1);
insert into trip (trip_name, user_id) values ('Ukraine', 4);
insert into trip (trip_name, user_id) values ('Norway', 4);
insert into trip (trip_name, user_id) values ('Ecuador', 4);
insert into trip (trip_name, user_id) values ('Norway', 1);
insert into trip (trip_name, user_id) values ('Czech Republic', 3);
insert into trip (trip_name, user_id) values ('Philippines', 3);
insert into trip (trip_name, user_id) values ('Poland', 1);
insert into trip (trip_name, user_id) values ('Colombia', 4);
insert into trip (trip_name, user_id) values ('China', 4);
insert into trip (trip_name, user_id) values ('Indonesia', 2);
insert into trip (trip_name, user_id) values ('Vietnam', 2);
insert into trip (trip_name, user_id) values ('Palestinian Territory', 4);
insert into trip (trip_name, user_id) values ('Czech Republic', 3);
insert into trip (trip_name, user_id) values ('China', 3);
insert into trip (trip_name, user_id) values ('China', 4);
insert into trip (trip_name, user_id) values ('United States', 4);
insert into trip (trip_name, user_id) values ('Ireland', 1);
insert into trip (trip_name, user_id) values ('Indonesia', 2);
insert into trip (trip_name, user_id) values ('Poland', 1);
insert into trip (trip_name, user_id) values ('Russia', 1);
insert into trip (trip_name, user_id) values ('France', 3);
insert into trip (trip_name, user_id) values ('Malaysia', 1);
insert into trip (trip_name, user_id) values ('Portugal', 1);
insert into trip (trip_name, user_id) values ('Venezuela', 2);
insert into trip (trip_name, user_id) values ('Latvia', 3);
insert into trip (trip_name, user_id) values ('Mexico', 3);
insert into trip (trip_name, user_id) values ('Indonesia', 2);
insert into trip (trip_name, user_id) values ('Philippines', 3);
insert into trip (trip_name, user_id) values ('China', 2);
insert into trip (trip_name, user_id) values ('Poland', 3);
insert into trip (trip_name, user_id) values ('Philippines', 3);
insert into trip (trip_name, user_id) values ('Indonesia', 3);
insert into trip (trip_name, user_id) values ('Indonesia', 1);
insert into trip (trip_name, user_id) values ('Portugal', 2);
insert into trip (trip_name, user_id) values ('China', 4);
insert into trip (trip_name, user_id) values ('Belarus', 3);
insert into trip (trip_name, user_id) values ('Greece', 3);
insert into trip (trip_name, user_id) values ('Indonesia', 2);
insert into trip (trip_name, user_id) values ('France', 4);
insert into trip (trip_name, user_id) values ('Mexico', 2);
insert into trip (trip_name, user_id) values ('Indonesia', 4);
insert into trip (trip_name, user_id) values ('Thailand', 3);
insert into trip (trip_name, user_id) values ('Thailand', 2);
insert into trip (trip_name, user_id) values ('Poland', 4);
insert into trip (trip_name, user_id) values ('Portugal', 1);
insert into trip (trip_name, user_id) values ('Indonesia', 2);
insert into trip (trip_name, user_id) values ('Peru', 3);
insert into trip (trip_name, user_id) values ('China', 2);
insert into trip (trip_name, user_id) values ('Yemen', 2);

insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('France', '42 Eliot Crossing', '2022-10-21', NOW(), 'Self-enabling', 36);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Peru', '0 Stuart Street', '2023-03-30', NOW(), 'eco-centric', 47);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Canada', '5 Stone Corner Park', '2022-10-21', NOW(), 'client-server', 45);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Denmark', '31989 Evergreen Circle', '2023-01-02', NOW(), 'responsive', 45);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Japan', '58 Tennessee Place', '2023-05-08', NOW(), 'heuristic', 28);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '2 Sugar Court', '2023-02-03', NOW(), 'Object-based', 14);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Ukraine', '16 Hermina Parkway', '2022-09-15', NOW(), 'Horizontal', 13);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Indonesia', '3153 Prairieview Court', '2023-07-04', NOW(), 'Graphical User Interface', 45);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '813 David Hill', '2022-11-03', NOW(), 'protocol', 18);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Gambia', '225 Morrow Crossing', '2022-10-22', NOW(), 'bottom-line', 11);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Argentina', '537 Arrowood Hill', '2022-07-24', NOW(), 'context-sensitive', 44);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('France', '3054 Weeping Birch Park', '2022-11-27', NOW(), 'core', 26);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Poland', '178 Mayfield Trail', '2022-11-30', NOW(), 'Polarised', 9);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Philippines', '129 Valley Edge Terrace', '2023-02-22', NOW(), 'Phased', 30);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '58713 Porter Way', '2022-11-14', NOW(), 'structure', 4);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('France', '6 Iowa Trail', '2022-12-03', NOW(), 'impactful', 20);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('United States', '859 Farragut Avenue', '2022-09-05', NOW(), 'real-time', 5);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '8474 Starling Road', '2023-06-27', NOW(), 'groupware', 26);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '25775 Bellgrove Crossing', '2023-05-16', NOW(), 'bifurcated', 19);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Philippines', '5122 Banding Pass', '2022-12-28', NOW(), 'artificial intelligence', 7);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Indonesia', '88 Anzinger Hill', '2023-07-01', NOW(), 'attitude', 7);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Malaysia', '61500 Gale Trail', '2023-02-14', NOW(), 'initiative', 32);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '31 Cordelia Terrace', '2023-03-05', NOW(), 'dedicated', 33);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Indonesia', '45 Chive Center', '2023-01-28', NOW(), 'Triple-buffered', 32);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Philippines', '5 Lillian Court', '2022-12-29', NOW(), 'function', 12);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '98852 Sutherland Lane', '2022-08-31', NOW(), 'moderator', 8);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Germany', '5 Fair Oaks Trail', '2022-11-18', NOW(), 'task-force', 27);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Tunisia', '02 Arizona Way', '2022-12-28', NOW(), 'multimedia', 49);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Indonesia', '1968 Bayside Trail', '2023-06-16', NOW(), 'Public-key', 6);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Greece', '3 Bartillon Trail', '2022-08-23', NOW(), 'real-time', 2);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '6888 Huxley Court', '2023-04-29', NOW(), 'alliance', 12);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Argentina', '3421 Longview Road', '2022-08-16', NOW(), 'website', 26);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '3 Kensington Pass', '2023-02-01', NOW(), 'Extended', 8);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Brazil', '66 Hollow Ridge Hill', '2023-05-31', NOW(), 'user-facing', 39);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Portugal', '019 Karstens Circle', '2022-12-15', NOW(), 'Progressive', 18);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('South Korea', '55 Nelson Park', '2023-03-24', NOW(), 'needs-based', 41);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '535 Calypso Pass', '2022-08-07', NOW(), 'help-desk', 43);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Palestinian Territory', '234 Westend Crossing', '2023-04-14', NOW(), 'parallelism', 3);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Ukraine', '96219 Stuart Circle', '2022-07-24', NOW(), 'pricing structure', 22);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('United States', '857 Surrey Plaza', '2023-02-11', NOW(), 'installation', 35);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '3 Cardinal Crossing', '2022-12-10', NOW(), 'implementation', 32);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Palestinian Territory', '02358 Scott Circle', '2023-04-07', NOW(), 'groupware', 44);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '643 Marcy Crossing', '2022-08-08', NOW(), 'Future-proofed', 7);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Indonesia', '7 Beilfuss Way', '2023-04-02', NOW(), 'tertiary', 10);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Brazil', '5313 Eagle Crest Way', '2023-02-27', NOW(), 'Compatible', 41);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Malaysia', '18441 Linden Lane', '2023-05-19', NOW(), 'contextually-based', 23);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('France', '5 Shopko Hill', '2022-08-30', NOW(), 'hierarchy', 36);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Japan', '9 Butterfield Court', '2023-02-05', NOW(), 'open system', 29);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Finland', '6 Arapahoe Plaza', '2023-06-09', NOW(), 'Organic', 1);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Colombia', '114 Annamark Street', '2022-10-20', NOW(), 'knowledge user', 20);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '5 Melby Plaza', '2023-07-01', NOW(), 'solution', 41);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Sweden', '92 Nelson Trail', '2022-10-19', NOW(), 'concept', 12);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Philippines', '40 Fairview Crossing', '2022-09-29', NOW(), 'Optional', 9);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Laos', '9 Sunnyside Drive', '2023-02-02', NOW(), 'workforce', 12);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Sweden', '26 Westridge Park', '2023-06-20', NOW(), 'application', 50);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('France', '40 Lien Court', '2022-12-10', NOW(), 'Managed', 7);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Ukraine', '9 Division Way', '2022-11-18', NOW(), 'responsive', 39);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Syria', '69 Goodland Hill', '2022-09-06', NOW(), 'real-time', 3);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('France', '7791 Holy Cross Drive', '2022-10-12', NOW(), 'content-based', 37);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Indonesia', '61995 Troy Crossing', '2022-08-25', NOW(), 'parallelism', 40);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Philippines', '56367 Brickson Park Way', '2022-09-17', NOW(), 'asymmetric', 11);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Philippines', '13037 Chinook Lane', '2022-12-23', NOW(), 'Persevering', 9);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '2717 Northfield Way', '2023-03-17', NOW(), 'national', 15);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Czech Republic', '3 Memorial Circle', '2022-10-11', NOW(), 'multi-state', 22);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Peru', '0165 Arapahoe Terrace', '2023-02-10', NOW(), 'adapter', 29);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('France', '3 Dennis Crossing', '2022-07-23', NOW(), 'info-mediaries', 11);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Ireland', '15204 Gale Center', '2022-10-17', NOW(), 'paradigm', 47);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '44692 8th Parkway', '2022-09-27', NOW(), 'Organized', 26);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '906 Bellgrove Crossing', '2023-06-27', NOW(), 'policy', 10);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Portugal', '25780 Heath Crossing', '2022-11-24', NOW(), 'Business-focused', 28);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Czech Republic', '30472 Veith Junction', '2022-10-08', NOW(), 'function', 25);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Philippines', '556 Westridge Pass', '2023-02-09', NOW(), 'Graphic Interface', 6);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Russia', '476 Sloan Circle', '2022-11-11', NOW(), 'Digitized', 5);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Indonesia', '3 Forster Circle', '2023-04-28', NOW(), 'grid-enabled', 26);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Nigeria', '5 Schurz Junction', '2023-01-04', NOW(), 'Ameliorated', 39);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '852 Transport Lane', '2022-08-10', NOW(), 'knowledge base', 46);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Vietnam', '1 Jenifer Trail', '2022-11-16', NOW(), 'algorithm', 20);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Portugal', '979 Bunker Hill Road', '2023-04-04', NOW(), 'didactic', 12);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Thailand', '1756 Schmedeman Court', '2022-10-26', NOW(), 'Diverse', 2);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Ukraine', '5954 Briar Crest Street', '2023-02-01', NOW(), 'Streamlined', 26);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Indonesia', '673 Prentice Lane', '2022-10-20', NOW(), 'system-worthy', 11);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Brazil', '745 Hudson Crossing', '2023-06-01', NOW(), 'circuit', 33);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Sweden', '6456 2nd Court', '2022-08-12', NOW(), 'challenge', 32);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Russia', '62 Forest Dale Circle', '2023-07-16', NOW(), 'static', 42);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Kazakhstan', '6677 Holy Cross Center', '2022-09-15', NOW(), 'encompassing', 9);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '66960 Mifflin Plaza', '2023-01-27', NOW(), 'homogeneous', 3);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Colombia', '36 Charing Cross Circle', '2023-06-17', NOW(), 'concept', 26);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '53961 Heath Park', '2023-01-27', NOW(), 'Integrated', 19);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Mexico', '3 Hagan Pass', '2023-03-17', NOW(), 'Open-source', 24);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Nicaragua', '193 Sutherland Street', '2023-04-11', NOW(), 'Fundamental', 43);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Russia', '51670 Hudson Court', '2023-01-28', NOW(), 'standardization', 14);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Czech Republic', '52 Prentice Junction', '2022-11-19', NOW(), 'cohesive', 3);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '6130 Shopko Pass', '2023-03-23', NOW(), 'Secured', 50);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Honduras', '95 Huxley Drive', '2023-03-30', NOW(), 'groupware', 39);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Indonesia', '2425 Monterey Hill', '2022-09-24', NOW(), 'full-range', 14);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Portugal', '080 Graedel Court', '2022-12-29', NOW(), 'Integrated', 45);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Peru', '2 Macpherson Way', '2022-09-27', NOW(), 'budgetary management', 32);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('United States', '801 Ridgeway Crossing', '2022-09-12', NOW(), 'matrices', 49);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('China', '845 Roth Terrace', '2023-03-27', NOW(), 'capacity', 2);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Indonesia', '517 Paget Place', '2022-11-21', NOW(), 'Automated', 19);