insert into users (first_name, last_name, email, password, address, city, state, country) values ('Peggy', 'Ede', 'pede0@csmonitor.com', '5lzPlXKIs', '571 Morningstar Street', 'Lynchburg', 'Virginia', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Kip', 'Swadden', 'kswadden1@army.mil', 'QemOCe', '1 Straubel Hill', 'Edmond', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Aubine', 'Haskew', 'ahaskew2@miitbeian.gov.cn', 's73kUa', '9 Gulseth Junction', 'Terre Haute', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Emmanuel', 'Radleigh', 'eradleigh3@cocolog-nifty.com', 'EvcJYOk', '202 Scott Park', 'Sacramento', 'California', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Windy', 'Pinn', 'wpinn4@hexun.com', 'gO3XZEd9', '682 Susan Way', 'Baltimore', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Alberta', 'Peto', 'apeto5@skype.com', 'aox4eR', '7 Toban Alley', 'Scottsdale', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Hercule', 'Siney', 'hsiney6@ft.com', 'uUMz6z', '71 Brickson Park Plaza', 'Fort Wayne', 'Indiana', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Randall', 'Maith', 'rmaith7@oakley.com', 'Gb17u7EUFb', '256 Starling Point', 'New Orleans', 'Louisiana', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Farlee', 'Prestedge', 'fprestedge8@phoca.cz', 'TTv8oMe699VI', '6391 Loeprich Road', 'West Palm Beach', 'Florida', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Marsha', 'Warrick', 'mwarrick9@bloomberg.com', 'MlE7NOV', '7464 Kingsford Hill', 'Des Moines', 'Iowa', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Pippa', 'Nappin', 'pnappina@netscape.com', 'zQHQBL', '52 Oak Valley Court', 'Evansville', 'Indiana', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Mycah', 'Arboin', 'marboinb@aboutads.info', 'xDRMb6RX', '62974 Hoepker Place', 'Pensacola', 'Florida', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Jo', 'Badrock', 'jbadrockc@ovh.net', 'UTewN63XaP', '2209 Kingsford Way', 'Greensboro', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Kial', 'Slesser', 'kslesserd@uiuc.edu', 'NbugBuTR3', '94 Doe Crossing Junction', 'Houston', 'Texas', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Corabel', 'Grossman', 'cgrossmane@dion.ne.jp', 'Pfca750t', '15 Elmside Way', 'Indianapolis', 'Indiana', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Coriss', 'Beau', 'cbeauf@geocities.jp', 'NGkRGc', '6315 Goodland Point', 'Saint Louis', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Amery', 'Bernardy', 'abernardyg@plala.or.jp', '6n3GXSnr7', '40441 Bayside Circle', 'Columbia', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Panchito', 'Girone', 'pgironeh@bizjournals.com', 'G6WGxzGSTo', '487 Oakridge Pass', 'Washington', 'District of Columbia', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Dory', 'Tumasian', 'dtumasiani@tinypic.com', 'RDcS03Ilx', '43 Hollow Ridge Park', 'Charleston', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Zena', 'Farnworth', 'zfarnworthj@forbes.com', 'xkVvQ4RLH7', '17 Iowa Point', 'Washington', 'District of Columbia', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Krysta', 'Fishly', 'kfishlyk@csmonitor.com', 'NyOaGklZrOa', '36 Fair Oaks Circle', 'Anaheim', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Culver', 'Sheldrake', 'csheldrakel@yelp.com', 'TjKP3t', '72 Browning Court', 'Atlanta', 'Georgia', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Bobbye', 'Calow', 'bcalowm@weibo.com', 'OoUz0v', '80615 Melody Drive', 'Young America', 'Minnesota', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Isaac', 'Pepperell', 'ipepperelln@jugem.jp', 'DTcFuiAm', '2200 Pond Plaza', 'Sacramento', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Elias', 'Leglise', 'elegliseo@topsy.com', 'cjHNTUzyG', '148 Roth Point', 'Springfield', 'Illinois', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Philly', 'Halgarth', 'phalgarthp@arizona.edu', 'OjgEFTPI7oLz', '94437 Eliot Center', 'Lawrenceville', 'Georgia', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Kerry', 'Monketon', 'kmonketonq@etsy.com', 'SLnrNdugNYm', '04990 Duke Point', 'Kansas City', 'Kansas', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Guillaume', 'Vermer', 'gvermerr@engadget.com', 'GJFRzqcbQ', '75857 Mccormick Parkway', 'Des Moines', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Reuven', 'Plaskitt', 'rplaskitts@prnewswire.com', 'DggMzII3s', '556 Kings Pass', 'Miami', 'Florida', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Aldo', 'Renton', 'arentont@stanford.edu', 'kOvtpLcjRx', '309 Sundown Circle', 'Orange', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Arnuad', 'Chilcott', 'achilcottu@paginegialle.it', 'qxSKwrH', '16711 Mayfield Lane', 'Atlanta', 'Georgia', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Hobey', 'Hugnin', 'hhugninv@toplist.cz', '83ln65DsHj9T', '2280 Shoshone Park', 'Jacksonville', 'Florida', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Flinn', 'Pessler', 'fpesslerw@stanford.edu', 'kx2HyJ4bdol0', '38 Golf Course Crossing', 'Detroit', 'Michigan', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Edouard', 'Babington', 'ebabingtonx@epa.gov', 'r24IzG', '53080 Blue Bill Park Parkway', 'Henderson', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Joshua', 'McLaughlin', 'jmclaughliny@ebay.co.uk', 'bqIxtZmsx', '64 Brown Center', 'Washington', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Sampson', 'Wolfers', 'swolfersz@amazon.com', 'INWj166cW00', '2 Aberg Drive', 'Pasadena', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Shea', 'Castille', 'scastille10@dion.ne.jp', 'cBrHkjy', '30 Paget Park', 'Albuquerque', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Celinka', 'Iliff', 'ciliff11@hhs.gov', 'ltuPDXD', '8 5th Road', 'Chattanooga', 'Tennessee', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Ciro', 'Isakson', 'cisakson12@tinyurl.com', 'QBsurui', '49165 Coleman Park', 'Los Angeles', 'California', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Bibbie', 'Bennetto', 'bbennetto13@ihg.com', 'dXHktX1', '13 Harbort Court', 'Tallahassee', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Gwendolen', 'Cordle', 'gcordle14@cornell.edu', 'LybZXSRBzZtj', '6 Brown Center', 'Birmingham', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Zahara', 'Faithfull', 'zfaithfull15@cyberchimps.com', 'McM7EUuvPIaQ', '8 Fuller Terrace', 'Bozeman', 'Montana', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Jere', 'Frangello', 'jfrangello16@hc360.com', 'sDfzjYB', '6 Lukken Place', 'Charlotte', 'North Carolina', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Emilie', 'MacConnal', 'emacconnal17@ebay.co.uk', '18PbI3', '5709 Schiller Parkway', 'Wilmington', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Hugibert', 'Semechik', 'hsemechik18@theglobeandmail.com', 'hPpRw9mMuZ', '108 Sunfield Parkway', 'Boston', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Ezmeralda', 'Daveridge', 'edaveridge19@kickstarter.com', 'pA5nddZk', '36410 Moose Circle', 'Melbourne', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Nanete', 'Strevens', 'nstrevens1a@ucoz.ru', 'qNTeT1', '918 Forest Drive', 'Prescott', 'Arizona', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Kermit', 'Crowther', 'kcrowther1b@icio.us', 'MYtEW30cMV', '6642 Roth Crossing', 'Portland', 'Oregon', 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Delores', 'Antognetti', 'dantognetti1c@smh.com.au', 'ZMEDeEvC34K', '9853 Mosinee Point', 'New Haven', null, 'United States');
insert into users (first_name, last_name, email, password, address, city, state, country) values ('Gardie', 'Tregian', 'gtregian1d@independent.co.uk', 'uy1cjGw5auv', '892 Grover Terrace', 'Springfield', 'Massachusetts', 'United States');

insert into trip (trip_name, user_id) values ('Indonesia', 8);
insert into trip (trip_name, user_id) values ('Portugal', 39);
insert into trip (trip_name, user_id) values ('Portugal', 40);
insert into trip (trip_name, user_id) values ('Thailand', 40);
insert into trip (trip_name, user_id) values ('Czech Republic', 26);
insert into trip (trip_name, user_id) values ('Canada', 22);
insert into trip (trip_name, user_id) values ('China', 9);
insert into trip (trip_name, user_id) values ('France', 49);
insert into trip (trip_name, user_id) values ('Syria', 28);
insert into trip (trip_name, user_id) values ('China', 35);
insert into trip (trip_name, user_id) values ('Brazil', 41);
insert into trip (trip_name, user_id) values ('Armenia', 22);
insert into trip (trip_name, user_id) values ('Costa Rica', 6);
insert into trip (trip_name, user_id) values ('Ethiopia', 39);
insert into trip (trip_name, user_id) values ('China', 37);
insert into trip (trip_name, user_id) values ('Ecuador', 20);
insert into trip (trip_name, user_id) values ('Russia', 10);
insert into trip (trip_name, user_id) values ('Indonesia', 35);
insert into trip (trip_name, user_id) values ('Kenya', 3);
insert into trip (trip_name, user_id) values ('Niger', 7);
insert into trip (trip_name, user_id) values ('Vietnam', 18);
insert into trip (trip_name, user_id) values ('China', 7);
insert into trip (trip_name, user_id) values ('Sierra Leone', 24);
insert into trip (trip_name, user_id) values ('Madagascar', 14);
insert into trip (trip_name, user_id) values ('Chad', 36);
insert into trip (trip_name, user_id) values ('Philippines', 26);
insert into trip (trip_name, user_id) values ('Canada', 38);
insert into trip (trip_name, user_id) values ('Saint Kitts and Nevis', 48);
insert into trip (trip_name, user_id) values ('Iran', 47);
insert into trip (trip_name, user_id) values ('Brazil', 48);
insert into trip (trip_name, user_id) values ('Argentina', 48);
insert into trip (trip_name, user_id) values ('Brazil', 10);
insert into trip (trip_name, user_id) values ('China', 44);
insert into trip (trip_name, user_id) values ('Russia', 39);
insert into trip (trip_name, user_id) values ('Brazil', 11);
insert into trip (trip_name, user_id) values ('China', 24);
insert into trip (trip_name, user_id) values ('Portugal', 5);
insert into trip (trip_name, user_id) values ('Ukraine', 37);
insert into trip (trip_name, user_id) values ('China', 14);
insert into trip (trip_name, user_id) values ('Poland', 11);
insert into trip (trip_name, user_id) values ('Philippines', 20);
insert into trip (trip_name, user_id) values ('Somalia', 21);
insert into trip (trip_name, user_id) values ('Pakistan', 12);
insert into trip (trip_name, user_id) values ('Uruguay', 8);
insert into trip (trip_name, user_id) values ('France', 6);
insert into trip (trip_name, user_id) values ('United States', 11);
insert into trip (trip_name, user_id) values ('China', 7);
insert into trip (trip_name, user_id) values ('Russia', 20);
insert into trip (trip_name, user_id) values ('Mexico', 34);
insert into trip (trip_name, user_id) values ('United States', 38);

insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Orbadiah', '605 Dwight Plaza', '2023-02-27', NOW(), 'mi nulla ac enim in', 9);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Vikki', '89 Main Lane', '2023-06-14', NOW(), 'ut tellus nulla ut erat id mauris', 14);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Borden', '69 Florence Center', '2023-02-05', NOW(), 'quisque porta volutpat erat quisque erat', 43);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Cris', '2 Debs Junction', '2022-09-18', NOW(), 'elit proin risus praesent lectus', 7);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Tiphany', '534 Ridgeview Pass', '2023-02-01', NOW(), 'nulla nisl nunc nisl duis bibendum', 23);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Lenna', '24815 Ilene Hill', '2023-06-22', NOW(), 'vel nisl duis ac nibh fusce', 8);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Sallie', '048 Fremont Point', '2023-01-10', NOW(), 'nulla suscipit ligula in lacus curabitur at ipsum ac', 29);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Oralee', '306 Menomonie Hill', '2022-09-29', NOW(), 'nulla pede ullamcorper augue a', 39);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Dorena', '8779 Summer Ridge Lane', '2022-08-15', NOW(), 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus', 9);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Calhoun', '20 Jackson Lane', '2022-07-27', NOW(), 'orci nullam molestie nibh in lectus', 11);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Merrie', '6251 Arkansas Way', '2022-08-16', NOW(), 'quis turpis eget elit sodales scelerisque mauris sit amet', 36);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Thomasin', '1930 Quincy Place', '2023-04-09', NOW(), 'dui vel nisl duis ac nibh', 42);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Elaine', '24866 Sachs Lane', '2022-10-16', NOW(), 'interdum venenatis turpis enim blandit mi in porttitor pede justo', 34);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Jacinthe', '434 Hoffman Lane', '2023-06-29', NOW(), 'proin leo odio porttitor id consequat in consequat', 44);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Andy', '42584 Stoughton Hill', '2023-06-11', NOW(), 'vel ipsum praesent blandit lacinia erat vestibulum sed magna', 32);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Jeramey', '426 Mitchell Junction', '2022-11-19', NOW(), 'tortor quis turpis sed ante', 46);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Dyanne', '7 Arrowood Court', '2022-08-02', NOW(), 'lobortis sapien sapien non mi integer ac neque duis', 14);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Christabel', '254 Johnson Court', '2023-02-09', NOW(), 'vel ipsum praesent blandit lacinia erat vestibulum sed', 16);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Karissa', '5 Clove Lane', '2022-07-15', NOW(), 'semper porta volutpat quam pede lobortis ligula', 28);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Mace', '29 Bluejay Junction', '2022-11-02', NOW(), 'nulla elit ac nulla sed vel enim sit amet', 11);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Stacy', '136 La Follette Junction', '2022-09-27', NOW(), 'id nulla ultrices aliquet maecenas leo', 27);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Miguelita', '907 Helena Parkway', '2022-09-27', NOW(), 'cubilia curae nulla dapibus dolor vel est donec odio justo', 6);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Othilie', '61155 Sauthoff Point', '2023-02-05', NOW(), 'ultrices vel augue vestibulum ante ipsum primis in faucibus', 10);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Ivy', '170 Northland Junction', '2022-08-13', NOW(), 'parturient montes nascetur ridiculus mus etiam vel augue vestibulum', 20);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Honor', '525 Jackson Drive', '2023-05-24', NOW(), 'habitasse platea dictumst aliquam augue quam sollicitudin vitae', 35);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Roxine', '74242 Morningstar Street', '2023-02-12', NOW(), 'vel lectus in quam fringilla rhoncus mauris', 2);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Sada', '2748 Meadow Vale Street', '2022-10-04', NOW(), 'tincidunt ante vel ipsum praesent blandit lacinia erat', 3);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Liza', '06 Summerview Junction', '2023-01-08', NOW(), 'ut ultrices vel augue vestibulum ante ipsum', 4);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Marlena', '787 Stoughton Terrace', '2023-06-29', NOW(), 'auctor sed tristique in tempus sit amet sem', 38);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Howard', '06567 Harbort Parkway', '2023-04-13', NOW(), 'ridiculus mus etiam vel augue vestibulum rutrum rutrum', 48);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Cazzie', '670 Pearson Park', '2022-09-14', NOW(), 'aenean lectus pellentesque eget nunc donec', 41);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Miltie', '1953 Armistice Drive', '2023-03-01', NOW(), 'est congue elementum in hac', 12);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Ardra', '1 5th Point', '2023-06-10', NOW(), 'odio justo sollicitudin ut suscipit a feugiat et', 2);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Harmonie', '250 Center Pass', '2023-04-05', NOW(), 'vehicula consequat morbi a ipsum integer a', 20);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Jephthah', '870 Northwestern Avenue', '2023-01-02', NOW(), 'est et tempus semper est quam pharetra magna', 7);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Buffy', '70443 Esker Alley', '2022-12-12', NOW(), 'nulla ultrices aliquet maecenas leo odio condimentum id luctus', 43);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Clarence', '825 Sachs Lane', '2023-03-02', NOW(), 'vestibulum eget vulputate ut ultrices vel augue vestibulum ante', 43);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Robinette', '1 East Pass', '2022-08-31', NOW(), 'velit eu est congue elementum in', 11);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Valentine', '8 Brickson Park Place', '2022-11-10', NOW(), 'blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing', 42);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Simonne', '4 Ridgeview Pass', '2023-02-20', NOW(), 'arcu adipiscing molestie hendrerit at', 30);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Monro', '1 Twin Pines Court', '2023-06-02', NOW(), 'ipsum praesent blandit lacinia erat vestibulum sed magna', 7);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Frankie', '48 Manitowish Point', '2022-09-26', NOW(), 'sapien iaculis congue vivamus metus', 34);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Tobi', '0 Barnett Way', '2023-06-14', NOW(), 'est et tempus semper est quam pharetra magna ac', 24);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Collin', '7959 Barnett Parkway', '2022-09-15', NOW(), 'augue quam sollicitudin vitae consectetuer eget rutrum at lorem', 34);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Sharon', '7 Colorado Park', '2022-08-10', NOW(), 'molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque', 24);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Windham', '269 Dixon Way', '2022-12-15', NOW(), 'augue vestibulum rutrum rutrum neque aenean', 8);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Lancelot', '17324 Buena Vista Alley', '2022-09-08', NOW(), 'quam pede lobortis ligula sit amet', 41);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Darrelle', '0 Oxford Hill', '2023-05-23', NOW(), 'donec semper sapien a libero nam dui proin', 40);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Cristi', '163 Oakridge Point', '2022-10-17', NOW(), 'proin eu mi nulla ac', 9);
insert into place (place_name, place_address, trip_date, trip_time, notes, trip_id) values ('Ingaberg', '775 Starling Parkway', '2023-04-23', NOW(), 'aliquam augue quam sollicitudin vitae', 39);